name = " Sakia Landing Page"
description = "An elegant open source landing page theme."
homepage = "https://github.com/duniter/sakia-wallet.org"
features = ["social", "images" ]
min_version= 0.14

[author]
     name = "inso"

[original]
    author =  "swcool"
    homepage = "https://github.com/swcool/landing-page-theme"
    repo = "https://github.com/swcool/landing-page-theme"

